### PR TITLE
add default elevation mask angle of 10 degrees

### PR DESCRIPTION
**Pull request by denniszollo**
I want to put this in the release - have a hitl test going to see how much it affects performance.  My hunch is it helps a lot.

### CODE REVIEW

**Comment by ljbade** [comment]
What hash are the HITL results under?

**Comment by denniszollo** [comment]
Here's a good view: no longer going into the release:
http://sbp-log-analysis.swiftnav.com/#/d/0/q/x/firmware/y/metric/f/metric/p/all/f/firmware/sv/piksi_firmware_v0.21-209-geb0b6a8.hex%2Cpiksi_firmware_leith2-v0.21.hex%2Cpiksi_firmware_v0.21.hex/st/1?_k=v8j214

**Comment by denniszollo** [comment]
Caused some huge outlier runs so this is out for now:
http://sbp-log-analysis.swiftnav.com/#/d/0/q/x/firmware/y/scenario/f/firmware/sv/piksi_firmware_v0.21-209-geb0b6a8.hex%2Cpiksi_firmware_leith2-v0.21.hex%2Cpiksi_firmware_v0.21.hex/f/metric/sv/SolutionOutlierTest%2Fmetrics%2Ffixed%2Fdistance%2Facc%2Fsep99/st/2?_k=ylurmy

**Comment by ljbade** [comment]
Wow we need to figure out these damn outliers!

**Pull request closed without merging**
