### PR TITLE
Settings pdf

### PR DESCRIPTION
**Pull request by denniszollo**
update settings doc

### CODE REVIEW

**Comment by denniszollo** [comment]
please ignore - accidental extra commits for now

**Comment by denniszollo** [comment]
@cbeighley

**Comment by cbeighley** [comment]
Under 3.1 ext events, it says "Requires NAP firmware ¿= 0.12."

**Comment by cbeighley** [comment]
amb init var and new amb var have changed to 1e25. Can we generate these default values in the pdf programatically?

**Comment by denniszollo** [comment]
definitely, but I think it is kind of hard from a dependency perspective.  Almost like the code that generates the settings would need to checkout a firmware version as part of itself.

**Comment by denniszollo** [comment]
This kind of speaks to why the settings.pdf belongs in the firmware repo.

**Comment by denniszollo** [comment]
Although I don't think it would be bad to procedurally enforce that when people muck with the settings they have to update the documentation .yaml for this pdf and the console.

**Comment by cbeighley** [comment]
Looks good to me. Maybe the README.md should show where the settings pdf can be found?

**Pull request merged**
