### PR TITLE
Ensure setup.sh has pip on Linux

### PR DESCRIPTION
**Pull request by cbeighley**
@mookerji

### CODE REVIEW

**Comment by cbeighley** [comment]
Version of arm tools also wasn't available in repo - @fnoble @gsmcmullin okay to change?

**Comment by fnoble** [comment]
Should be fine. Did you try building the firmware with the new tools?

**Comment by cbeighley** [comment]
Yes, it builds.

**Comment by ungureanuvladvictor** [comment]
Compiler is good, I am using it for some time with the firmware.

**Pull request merged**
