### PR TITLE
update settings.pdf for new settings

### PR DESCRIPTION
**Pull request by denniszollo**

### CODE REVIEW

**Comment by denniszollo** [comment]
@drewshannon @cbeighley 
Our settings doc was pretty out of date - please let me know if you see any typos or issues.

**Comment by ljbade** [comment]
Hmm from `manage.c`:
`SETTING("acquisition", "sbas enabled", sbas_enabled, TYPE_BOOL);`

That was added recently.

**Comment by denniszollo** [comment]
@ljbade - perhaps I should merge this one, tag as version 0.21, and then merge one with the latest settings.  Our settings stuff is a little discombobulated.  The settings live in the firmware, and the settings documentation lives in piksi_tools/console/settings.yaml .  I have an offline script to generate this PDF, which still lives in the firmware.  We have a plan for the future (see https://github.com/swift-nav/piksi_tools/pull/54), but it's still this way for now.

**Comment by ljbade** [comment]
@denniszollo Ah I see. Fair enough.

**Pull request merged**
