### PR TITLE
Use ANSI sequence to clear line.

### PR DESCRIPTION
**Pull request by gsmcmullin**

### CODE REVIEW

**Comment by fnoble** [comment]
Will this work on Windows? (maybe we don't care)

What are the benefits of doing it this was?

**Comment by gsmcmullin** [comment]
It spewed unprintable binary for me on Linux.
I haven't tested on Windows.

**Comment by fnoble** [comment]
@cbeighley : any comments? the fix looks good to me but presumably this worked in some context before?

**Comment by gsmcmullin** [comment]
It doesn't work in Windows, but Windows doesn't get this far.  It aborts in serial_link.py if the port doesn't exist.  The old code doesn't work in Windows either, chr(3) prints a heart.  I guess it worked on OS X before.

**Comment by fnoble** [comment]
lol, ok, wtf is 0x03 "End of text" anyhow?

**Pull request merged**
