### PR TITLE
Raim repair report

### PR DESCRIPTION
**Pull request by henryhallam**
We have to have soemthing like this, or it'll be very difficult to compare HITL results.

@fnoble @cbeighley @denniszollo @kovach @mookerji

### CODE REVIEW

**Comment by cbeighley** [comment]
Standardize on `LOG_INFO` or `LOG_WARNING` for RAIM repair repair re: https://github.com/swift-nav/libswiftnav/pull/189

**Comment by henryhallam** [comment]
ok, went with LOG_WARNING since with current RAIM thresholds, RAIM repairs are indicative of a truly crazy (not merely poor) observation.

**Comment by cbeighley** [comment]
Update to merged libswiftnav commit and then good to merge

**Comment by henryhallam** [comment]
retest this please

**Pull request merged**
