### PR TITLE
Update the sbp rev and remove bad dependency sequencing

### LINKED ISSUE #320: setup.sh (via ansible playbook) fails to install 'construct', required by 'sbp'
Attempting to use 'setup.sh -x install' on a fresh machine (tested: Ubuntu 12.04, Debian Jessie) fails at 

TASK: [common_ubuntu | Install python Enthought dependencies]

[Full log](https://gist.github.com/henryhallam/5c637b3c0e43545dae29)

The problem appears to be that the '[construct](https://pypi.python.org/pypi/construct)' package is needed by '[sbp](https://pypi.python.org/pypi/sbp/0.27)''s setup.py - it is not merely a runtime dependency of the package.  In Debian parlance it might be considered a 'Pre-Depends'.  The ansible playbook lists both 'construct' and 'sbp' in the same invocation of 'pip install' (setup/ansible/roles/common_ubuntu/tasks/sys_deps.yml line 55):
```
pip install traits traitsui pyserial pylibftdi
             pyparsing==1.5.7 pygments intelhex six construct sbp==0.27
```

pip 'collects' (i.e. downloads) the tarball for each package, in the order given, but does not attempt to install them in the same order.

As a workaround, running 'sudo pip install construct' and rerunning setup.sh will do the job.

### PR DESCRIPTION
**Pull request by mfine**
Fix for dependency issues on `construct`. Fixes #320.

/cc @henryhallam @mookerji

### CODE REVIEW

**Comment by mfine** [comment]
Please retest.

**Comment by mfine** [comment]
retest this please

**Comment by mfine** [comment]
Hmmm...

```
+ git describe
+ export GIT_DESCRIBE=v0.15-rc0-15-g45a2cb1
+ mkdir artifacts
mkdir: cannot create directory ‘artifacts’: File exists
Build step 'Use builders from another project' marked build as failure
```

**Comment by mookerji** [comment]
retest this please

**Comment by mookerji** [comment]
Does the libsbp 0.29 version have any effect on any of the tools in scripts/?

**Comment by mfine** [comment]
Yeah, there were changes to the scripts - good catch. Updated to reflect the new new paths.

**Comment by mfine** [comment]
Able to get a good clean build on a clean vm.

**Pull request merged**
