### PR TITLE
Change cutoff frequency

### PR DESCRIPTION
**Pull request by Paakkit**
Please do not merge this until https://github.com/swift-nav/libswiftnav/pull/324 is merged.

### CODE REVIEW

**Comment by ljbade** [comment]
Can you update the libswiftnav to point to the required PR?

**Comment by cbeighley** [comment]
Have we done HITL testing on this?

**Comment by ljbade** [comment]
@cbeighley Once we finish tuning/testing the filter we need to go back and redo (improve) the way we disable sats for PVT/RTK from the cn0.

Currently a sat straddling a low cn0 will be constantly added and removed from the RTK solution slowing down IAR.

A simple hysteresis should work well with a smooth filter.

**Comment by Paakkit** [comment]
@ljbade Could you please take a look and explain why travis build is complaining?

**Comment by ljbade** [comment]
Looks like a network problem, the apt-get for the ARM GCC failed to authenticate the server.

**Comment by ljbade** [comment]
Ill restart it

**Comment by Paakkit** [comment]
@jacobmcnamee PR updated, waiting merge of https://github.com/swift-nav/libswiftnav/pull/324

**Comment by rge-exafore** [comment]
HITL test: piksi_firmware_v0.21-209-g1a8fb78.hex

**Comment by rge-exafore** [comment]
HITL: piksi_firmware_v0.21-209-g1a8fb78.hex

**Comment by valeri-atamaniouk** [comment]
Replaced by https://github.com/swift-nav/piksi_firmware/pull/723

**Pull request closed without merging**
