### PR TITLE
Work Saturday changes into v0.20

### PR DESCRIPTION
**Pull request by mfine**
Bring in the work Saturday changes.

/cc @henryhallam @cbeighley

### CODE REVIEW

**Comment by henryhallam** [comment]
LGTM as far as the end-of-week stuff, but the libswiftnav repo tree is getting pretty tangled.  Do we have to have separate v0.19 and v0.20 branches for libswiftnav or can we convince ourselves it's safe to point the piksi_firmware release branches at master libswiftnav?

**Comment by henryhallam** [comment]
i.e. I'm confused about whether the various fixes-to-fixes of the dgnss satellite rebasing are in the libswiftnav that this points to

**Comment by cbeighley** [comment]
@henryhallam v0.19-branch of piksi_firmware points to v0.19-branch of libswiftnav, which has the correct baseline rebasing stuff now.

**Comment by mfine** [comment]
@henryhallam libswiftnav changes here are https://github.com/swift-nav/libswiftnav/compare/cc4474e8f7240594b43d7982f01aaf069b7893e5...v0.20-branch

**Comment by fnoble** [comment]
Looks like this made it in via some other route... closing

**Pull request closed without merging**
