### PR TITLE
WIP: Adjust carrier phase for receiver clock error

### PR DESCRIPTION
**Pull request by ljbade**
Attempts to fix the large drift between pseudorange and carrier-phase @denniszollo observed.

@denniszollo Can you test this?

### CODE REVIEW

**Comment by ljbade** [comment]
HITL:  piksi_firmware_leith2-v0.21-284-g62d04ae.hex

**Comment by ljbade** [comment]
Hmm HITL tests have lots of errors.

**Comment by ljbade** [comment]
Other things to look at:
Check carrier phase offset only set once
Check use of carrier phase range rate
Check doppler issues @nsirola found
Try disabling clock correction to pseudorange

**Comment by ljbade** [comment]
After following discussion on Ublox clock error, going to try removing the first correction altogether.

**Comment by ljbade** [comment]
HITL: piksi_firmware_leith2-v0.21-285-gb55d384.hex

**Comment by nsirola** [comment]
I was wondering about this correction as well because pseudorange by definition is allowed to have arbitrary clock error. This change looks good to me.

**Comment by ljbade** [comment]
Closing this, as it appears the current RTK filter does not work without this correction.

**Pull request closed without merging**
