### PR TITLE
Use lock counter from both rover and base

### PR DESCRIPTION
**Pull request by fnoble**
**Why:** When several satellites drop at once causing the total number to go below 4 the filter doesn't update. When the satellites come back the filter needs to know that their integer ambiguity has changed. If the filter is unable to detect this then very large baseline outliers are generated and the filter never recovers. For base observations this was done by the lock counter mechanism but there is currently no analogue for the local observations.

**How:** Extend the lock counter mechanism to the rover as well. To do this we add a lock counter field to the single differences and make this equal to the _sum_ of the base and rover lock counters (lock counters are typically incremented to indicate a loss of lock). We now check this combined lock counter values for changes.

**Testing:** Tested on the bench by wiggling the antenna cable. Previously it was quite easy to cause a large error but with this change I have been unable to cause a large baseline outlier to occur. Further testing required on HITL as well as further manual testing.

review plz: @kovach 
fyi: @cbeighley @mookerji @denniszollo

### CODE REVIEW

**Comment by mookerji** [comment]
mon€y

**Comment by fnoble** [comment]
HITL looks good (finally)

**Comment by cbeighley** [comment]
Looks good. Have you bumped libswiftnav to master?

**Comment by fnoble** [comment]
Yup

**Comment by cbeighley** [comment]
merge at will

**Pull request merged**
